// sidebars.js

const sidebars = {
  tutorialSidebar: [
    {
      type: "doc",
      id: "intro", // archivo docs/intro.md
      label: "Introducción",
    },
    {
      type: "category",
      label: "Frontend",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Internet",
          collapsed: true,
          items: [
            "frontend/internet/fundamentos",
            "frontend/internet/historia",
            "frontend/internet/conectando",
            "frontend/internet/navegadores",
          ],
        },
        {
          type: "category",
          label: "HTML",
          collapsed: true,
          items: [
            "frontend/html/estructuraBasica",
            "frontend/html/elementosSemanticos",
            "frontend/html/etiquetasAtributos",
            "frontend/html/creacionContenidos",
            "frontend/html/formateoTexto",
            "frontend/html/quotationsCitations",
            "frontend/html/listas",
            "frontend/html/elementosMeta",
            "frontend/html/elementosSpan",
            "frontend/html/enlaces",
            "frontend/html/favicon",
            "frontend/html/tablas",
            "frontend/html/canvas",
            "frontend/html/bloqueVSlinea",
            "frontend/html/div",
            "frontend/html/caracteresEspeciales",
            "frontend/html/entidades",
            "frontend/html/class",
            "frontend/html/id",
            "frontend/html/computerCode",
            "frontend/html/contenidoEmbebido",
            "frontend/html/imagenes",
            "frontend/html/audio",
            "frontend/html/accesibilidad",
            "frontend/html/normativaEspanola",
          ],
        },
        {
          type: "category",
          label: "formularios",
          collapsed: true,
          items: [
            "frontend/formularios/introduccion",
            "frontend/formularios/webInteractiva",
            "frontend/formularios/variabilidadDatos",
            "frontend/formularios/envioRecepcion",
            "frontend/formularios/servidorWeb",
            "frontend/formularios/getPost",
            "frontend/formularios/action",
            "frontend/formularios/target",
            "frontend/formularios/method",
            "frontend/formularios/autocomplete",
            "frontend/formularios/novalidate",
            "frontend/formularios/enctype",
            "frontend/formularios/rel",
            "frontend/formularios/inputType",
            "frontend/formularios/label",
            "frontend/formularios/select",
            "frontend/formularios/textArea",
            "frontend/formularios/button",
            "frontend/formularios/fieldset",
            "frontend/formularios/legend",
            "frontend/formularios/datalist",
            "frontend/formularios/output",
            "frontend/formularios/optgroup",
            "frontend/formularios/option",
            "frontend/formularios/inputButton",
            "frontend/formularios/inputCheckbox",
            "frontend/formularios/inputColor",
            "frontend/formularios/inputDate",
            "frontend/formularios/inputEmail",
            "frontend/formularios/inputFile",
            "frontend/formularios/inputHidden",
            "frontend/formularios/inputImage",
            "frontend/formularios/inputMonth",
            "frontend/formularios/inputNumber",
            "frontend/formularios/inputPassword",
            "frontend/formularios/inputRadio",
            "frontend/formularios/inputRange",
            "frontend/formularios/inputReset",
            "frontend/formularios/inputSearch",
            "frontend/formularios/inputSubmit",
            "frontend/formularios/inputTel",
            "frontend/formularios/inputText",
            "frontend/formularios/inputTime",
            "frontend/formularios/inputURL",
            "frontend/formularios/inputWeek",
          ],
        },
        {
          type: "category",
          label: "CSS",
          collapsed: true,
          items: [
            "frontend/css/fundamentos",
            "frontend/css/sintaxis",
            "frontend/css/comentarios",
            "frontend/css/colores",
            "frontend/css/background",
            "frontend/css/borders",
            "frontend/css/margin",
            "frontend/css/padding",
            "frontend/css/height&width",
            "frontend/css/boxModel",
            "frontend/css/outline",
            "frontend/css/text",
            "frontend/css/fuentes",
            "frontend/css/icons",
            "frontend/css/links",
            "frontend/css/listas",
            "frontend/css/tablas",
            "frontend/css/display",
            "frontend/css/maxWidth",
            "frontend/css/position",
            "frontend/css/zIndex",
            "frontend/css/overflow",
            "frontend/css/float",
            "frontend/css/inlineBlock",
            "frontend/css/align",
            "frontend/css/combinators",
            "frontend/css/pseudoclases",
            "frontend/css/pseudoelementos",
            "frontend/css/opacity",
            "frontend/css/selectoresAtributos",
            "frontend/css/unidadesMedida",
            "frontend/css/important",
            "frontend/css/especificidad",
          ],
        },
        {
          type: "category",
          label: "CSS-Avanzado",
          collapsed: true,
          items: [
            "frontend/css2/borderRadius",
            "frontend/css2/borders",
            "frontend/css2/gradient",
            "frontend/css2/shadow",
            "frontend/css2/textEffect",
            "frontend/css2/2D",
            "frontend/css2/3D",
            "frontend/css2/transition",
            "frontend/css2/tooltips",
            "frontend/css2/animation",
            "frontend/css2/imagenesReflejadas",
            "frontend/css2/mascara",
            "frontend/css2/button",
            "frontend/css2/paginacion",
            "frontend/css2/multiplesColumnas",
            "frontend/css2/variables",
            "frontend/css2/mediaQueries",
            "frontend/css2/imagenes",
          ],
        },
        {
          type: "category",
          label: "Accesibilidad y Usabilidad",
          collapsed: true,
          items: [
            "frontend/ac&us/introduccion",
            "frontend/ac&us/dcu",
            "frontend/ac&us/dcp",
            "frontend/ac&us/mtu",
            "frontend/ac&us/ac&us",
            "frontend/ac&us/omcu",
            "frontend/ac&us/acc",
            "frontend/ac&us/neacc",
            "frontend/ac&us/pfacc",
            "frontend/ac&us/ddwacc",
            "frontend/ac&us/htvacc",
            "frontend/ac&us/tauw",
            "frontend/ac&us/efacc",
          ],
        },
        {
          type: "category",
          label: "javascript",
          collapsed: true,
          items: [
            "frontend/js/introduccion",
            "frontend/js/whyJS",
            "frontend/js/ubicacionArchivos",
            "frontend/js/sintaxis",
            "frontend/js/tiposDatos",
            "frontend/js/comentarios",
            "frontend/js/variables",
            "frontend/js/let",
            "frontend/js/const",
            "frontend/js/letVar",
            "frontend/js/ambito",
            "frontend/js/consoleLog",
            "frontend/js/hoisting",
            {
              type: "category",
              label: "Operadores",
              collapsed: true,
              items: [
                "frontend/js/operadores/operadores",
                "frontend/js/operadores/operadoresAritmeticos",
                "frontend/js/operadores/operadoresAsignacion",
                "frontend/js/operadores/operadoresComparacion",
                "frontend/js/operadores/operadoresConcatenacion",
                "frontend/js/operadores/operadoresLogicos",
                "frontend/js/operadores/precedenciaOperadores",
              ],
            },
            {
              type: "category",
              label: "Funciones",
              collapsed: true,
              items: [
                "frontend/js/funciones/funciones",
                "frontend/js/funciones/funcionesAnonimas",
                "frontend/js/funciones/funcionesAutoEjecutables",
                "frontend/js/funciones/funcionesPrimeraClase",
                "frontend/js/funciones/funcionesFlecha",
              ],
            },
            {
              type: "category",
              label: "Objetos_Literales",
              collapsed: true,
              items: [
                "frontend/js/objetos_literales/objetos_literales",
                "frontend/js/objetos_literales/this",
                "frontend/js/objetos_literales/todoSonObjetos",
              ],
            },
            {
              type: "category",
              label: "Strings",
              collapsed: true,
              items: [
                "frontend/js/strings/strings",
                "frontend/js/strings/metodosStrings",
                "frontend/js/strings/stringTemplates",
              ],
            },
            "frontend/js/numeros",
            {
              type: "category",
              label: "Arrays",
              collapsed: true,
              items: [
                "frontend/js/arrays/arrays",
                "frontend/js/arrays/interactuar",
                "frontend/js/arrays/metodosArrays",
              ],
            },
            "frontend/js/fechas",
            "frontend/js/math",
            "frontend/js/booleanos",
            "frontend/js/ifElse",
            "frontend/js/switch",
            {
              type: "category",
              label: "For",
              collapsed: true,
              items: [
                "frontend/js/for/for",
                "frontend/js/for/forIn",
                "frontend/js/for/forOf",
              ],
            },
            "frontend/js/while",
            "frontend/js/breakContinue",
            "frontend/js/iterables",
            "frontend/js/sets",
            "frontend/js/typeof",
            "frontend/js/expresionesRegulares",
            "frontend/js/clases",
            {
              type: "category",
              label: "DOM",
              collapsed: true,
              items: [
                "frontend/js/dom/dom",
                "frontend/js/dom/introduccion",
                "frontend/js/dom/acceso",
                "frontend/js/dom/estructura",
                "frontend/js/dom/eventos",
                "frontend/js/dom/eventosUsuario",
                "frontend/js/dom/manipulacion",
                "frontend/js/dom/renderizacionReflujos",
              ],
            },
            "frontend/js/maps",
            "frontend/js/modulos",
            "frontend/js/depuracionCodigo",
            "frontend/js/asincronia",
          ],
        },
        {
          type: "category",
          label: "Programacion Orientada a Objetos",
          collapsed: true,
          items: [
            "frontend/poo/fundamentosPOO",
            "frontend/poo/objetos&prototipos",
            "frontend/poo/clases&metodos",
            "frontend/poo/herencia&polimorfismo",
            "frontend/poo/POOAplicada",
            "frontend/poo/buenasPracticas",
          ],
        },
        {
          type: "category",
          label: "Flexbox",
          collapsed: true,
          items: [
            "frontend/flex/introduccion",
            "frontend/flex/CSSvsFlexbox",
            "frontend/flex/ejesFlexbox",
            "frontend/flex/flexWrap",
            "frontend/flex/flexFlow",
            "frontend/flex/alignContent",
            "frontend/flex/order",
            "frontend/flex/flexGrow",
            "frontend/flex/flexShrink",
            "frontend/flex/flexBasis",
            "frontend/flex/alignSelf",
            {
              type: "category",
              label: "Actividades",
              collapsed: true,
              items: [
                "frontend/flex/actividades/actividadFlexWrap",
                "frontend/flex/actividades/actividadFlexFlow",
                "frontend/flex/actividades/actividadFlexGrow",
                "frontend/flex/actividades/actividadFlexShrink",
                "frontend/flex/actividades/proyectoNavbar",
                "frontend/flex/actividades/proyectoHero",
                "frontend/flex/actividades/proyectoGaleria",
                "frontend/flex/actividades/proyectoDemoInteractiva",
                "frontend/flex/actividades/proyectoFlexDemo",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Backend",
      collapsed: true,
      items: [
        "backend/introduction",
        {
          type: "category",
          label: "Bases de Datos Relacionales",
          collapsed: true,
          items: [
            "backend/databases/Modulo1_Que_es_una_base_de_datos_relacional",
            "backend/databases/Modulo2_Elementos_basicos_del_modelo_relacional",
            "backend/databases/Modulo3_Relaciones_y_cardinalidad",
            "backend/databases/Modulo4_Requisitos_de_informacion_y_diccionarios",
            "backend/databases/Modulo5_Modelado_conceptual_ER_UML",
            "backend/databases/Modulo6_Paso_a_modelo_logico_relacional",
            "backend/databases/Modulo7_Normalizacion",
            "backend/databases/Modulo8_Desnormalizacion_controlada",
            "backend/databases/Modulo9_Algebra_relacional_y_pensamiento_declarativo",
            "backend/databases/Modulo10_Joins_agrupaciones_y_filtros_avanzados",
            "backend/databases/Modulo11_Vistas_logicas_y_composicion_de_consulta",
            "backend/databases/Modulo12_Claves_e_integridad_referencial_avanzada",
            "backend/databases/Modulo13_Integridad_referencial_en_serio",
            "backend/databases/Modulo14_Validaciones_al_nivel_correcto_dominios_restricciones_y_reglas_de_negocio",
            "backend/databases/Modulo15_Tipos_de_dominios_practicos",
            "backend/databases/Modulo16_Tablas_puente_y_modelado_N-a-N",
            "backend/databases/Modulo17_Que_es_un_indice_y_como_usarlo",
            "backend/databases/Modulo18_Patrones_de_indexacion",
            "backend/databases/Modulo19_Planificacion_conceptual_de_consultas",
            "backend/databases/Modulo20_ACID_sin_humo",
            "backend/databases/Modulo21_Aislamiento_y_anomalias",
            "backend/databases/Modulo22_Modelo_de_privilegios_minimos",
            "backend/databases/Modulo23_Datos_sensibles_y_auditoria",
            "backend/databases/Modulo24_Consultas_parametrizadas_y_seguridad",
            "backend/databases/Modulo25_Capas_de_acceso_a_datos",
            "backend/databases/Modulo26_Control_de_cambios_del_esquema",
            "backend/databases/Modulo27_Pruebas_de_bases_de_datos",
            "backend/databases/Modulo28_Importacion_y_exportacion_fiable",
            "backend/databases/Modulo29_Vistas_materializadas_y_reportes",
            "backend/databases/Modulo30_Copias_de_seguridad_y_recuperacion",
            "backend/databases/Modulo31_Mantenimiento_de_indices_y_crecimiento",
            "backend/databases/Modulo32_Cambios_en_caliente",
            "backend/databases/Modulo33_Particionamiento_y_distribucion",
            "backend/databases/Modulo34_Replicacion_y_lectura_pesada",
            "backend/databases/Modulo35_Caches_y_colas",
            "backend/databases/Modulo36_Documentar_para_el_futuro",
          ],
        },
        {
          type: "category",
          label: "Fundamentos de la Web y Http",
          collapsed: true,
          items: [
            "backend/fundamentosWeb/introduction",
            "backend/fundamentosWeb/servidorWeb",
            "backend/fundamentosWeb/arquitecturaClienteServidor",
            "backend/fundamentosWeb/flujoPeticionHttp",
            {
              type: "category",
              label: "Componentes de la comunicacion Web",
              collapsed: true,
              items: [
                "backend/fundamentosWeb/componentesComunicacion/componentesComunicacion",
                "backend/fundamentosWeb/componentesComunicacion/direccionesPuertos",
                "backend/fundamentosWeb/componentesComunicacion/peticionRespuesta",
                "backend/fundamentosWeb/componentesComunicacion/metodosHttp",
                "backend/fundamentosWeb/componentesComunicacion/cabeceras",
                "backend/fundamentosWeb/componentesComunicacion/certificadosHTTP",
              ],
            },
            "backend/fundamentosWeb/dominiosDNSHosting",
            "backend/fundamentosWeb/conectandoloTodo",
            "backend/fundamentosWeb/direccionesIP",
            "backend/fundamentosWeb/devTools",
          ],
        },
        {
          type: "category",
          label: "Node.js",
          collapsed: true,
          items: [
            "backend/Node.js/introduction",
            "backend/Node.js/modulosGestionDependenciasNPM",
            "backend/Node.js/asincronia",
            "backend/Node.js/sistemaArchivosProcesos",
            "backend/Node.js/servidorWeb",
            "backend/Node.js/expressJS",
            "backend/Node.js/mongoDBMongoose",
            "backend/Node.js/seguridadBuenasPracticas",
          ],
        },
        {
          type: "category",
          label: "JSON",
          collapsed: true,
          items: [
            "backend/JSON/queEsJSON",
            "backend/JSON/tiposDatos",
            "backend/JSON/JSONObjetos",
            "backend/JSON/JSONNode",
            "backend/JSON/crearGenerar",
            "backend/JSON/guardarLeer",
            "backend/JSON/manipularJSON",
            "backend/JSON/consumirJSON",
            "backend/JSON/actualizarEliminar",
            "backend/JSON/validacionControlErrores",
            "backend/JSON/crud",
            "backend/JSON/clienteHTTP",
            "backend/JSON/paginacion",
            "backend/JSON/seguridad",
            "backend/JSON/exportarImportar",
          ],
        },
      ],
    },
  ],
};

export default sidebars;
