// sidebars.js

const sidebars = {
  tutorialSidebar: [
    {
      type: "doc",
      id: "intro", // archivo docs/intro.md
      label: "Introducción",
    },
    {
      type: "category",
      label: "Frontend",
      collapsed: true,
      items: [
        {
          type: "category",
          label: "Internet",
          collapsed: true,
          items: [
            "internet/fundamentos",
            "internet/historia",
            "internet/https",
            "internet/dominiosDNSHosting",
            "internet/trafico",
            "internet/navegadores",
            {
              type: "category",
              label: "Google",
              collapsed: true,
              items: [
                "internet/google/google",
                "internet/google/pageRank",
                "internet/google/hummingbird",
                "internet/google/rankbrain",
                "internet/google/SEO",
                "internet/google/SEM",
                "internet/google/googlebot",
              ],
            },
            "internet/conectando",
            "internet/cloudflareEdgeComputing",
            "internet/webSocketsHTTP2",
          ],
        },
        {
          type: "category",
          label: "HTML",
          collapsed: true,
          items: [
            "html/estructuraBasica",
            "html/elementosSemanticos",
            "html/etiquetasAtributos",
            "html/creacionContenidos",
            "html/formateoTexto",
            "html/quotationsCitations",
            "html/listas",
            "html/elementosMeta",
            "html/elementosSpan",
            "html/enlaces",
            "html/favicon",
            "html/tablas",
            "html/canvas",
            "html/bloqueVSlinea",
            "html/div",
            "html/caracteresEspeciales",
            "html/entidades",
            "html/class",
            "html/id",
            "html/computerCode",
            "html/contenidoEmbebido",
            "html/imagenes",
            "html/audio",
            "html/accesibilidad",
            "html/normativaEspanola",
          ],
        },
        {
          type: "category",
          label: "formularios",
          collapsed: true,
          items: [
            "formularios/introduccion",
            "formularios/webInteractiva",
            "formularios/variabilidadDatos",
            "formularios/envioRecepcion",
            "formularios/servidorWeb",
            "formularios/getPost",
            "formularios/action",
            "formularios/target",
            "formularios/method",
            "formularios/autocomplete",
            "formularios/novalidate",
            "formularios/enctype",
            "formularios/rel",
            "formularios/inputType",
            "formularios/label",
            "formularios/select",
            "formularios/textArea",
            "formularios/button",
            "formularios/fieldset",
            "formularios/legend",
            "formularios/datalist",
            "formularios/output",
            "formularios/optgroup",
            "formularios/option",
            "formularios/inputButton",
            "formularios/inputCheckbox",
            "formularios/inputColor",
            "formularios/inputDate",
            "formularios/inputEmail",
            "formularios/inputFile",
            "formularios/inputHidden",
            "formularios/inputImage",
            "formularios/inputMonth",
            "formularios/inputNumber",
            "formularios/inputPassword",
            "formularios/inputRadio",
            "formularios/inputRange",
            "formularios/inputReset",
            "formularios/inputSearch",
            "formularios/inputSubmit",
            "formularios/inputTel",
            "formularios/inputText",
            "formularios/inputTime",
            "formularios/inputURL",
            "formularios/inputWeek",
          ],
        },
        {
          type: "category",
          label: "CSS",
          collapsed: true,
          items: [
            "css/fundamentos",
            "css/sintaxis",
            "css/comentarios",
            "css/colores",
            "css/background",
            "css/borders",
            "css/margin",
            "css/padding",
            "css/height&width",
            "css/boxModel",
            "css/outline",
            "css/text",
            "css/fuentes",
            "css/icons",
            "css/links",
            "css/listas",
            "css/tablas",
            "css/display",
            "css/maxWidth",
            "css/position",
            "css/zIndex",
            "css/overflow",
            "css/float",
            "css/inlineBlock",
            "css/align",
            "css/combinators",
            "css/pseudoclases",
            "css/pseudoelementos",
            "css/opacity",
            "css/selectoresAtributos",
            "css/unidadesMedida",
            "css/important",
            "css/especificidad",
          ],
        },
        {
          type: "category",
          label: "CSS-Avanzado",
          collapsed: true,
          items: [
            "css2/borderRadius",
            "css2/borders",
            "css2/gradient",
            "css2/shadow",
            "css2/textEffect",
            "css2/2D",
            "css2/3D",
            "css2/transition",
            "css2/tooltips",
            "css2/animation",
            "css2/imagenesReflejadas",
            "css2/mascara",
            "css2/button",
            "css2/paginacion",
            "css2/multiplesColumnas",
            "css2/variables",
            "css2/mediaQueries",
            "css2/imagenes",
          ],
        },
        {
          type: "category",
          label: "Accesibilidad y Usabilidad",
          collapsed: true,
          items: [
            "ac&us/introduccion",
            "ac&us/dcu",
            "ac&us/dcp",
            "ac&us/mtu",
            "ac&us/ac&us",
            "ac&us/omcu",
            "ac&us/acc",
            "ac&us/neacc",
            "ac&us/pfacc",
            "ac&us/ddwacc",
            "ac&us/htvacc",
            "ac&us/tauw",
            "ac&us/efacc",
          ],
        },
        {
          type: "category",
          label: "javascript",
          collapsed: true,
          items: [
            "js/introduccion",
            "js/whyJS",
            "js/ubicacionArchivos",
            "js/sintaxis",
            "js/tiposDatos",
            "js/comentarios",
            "js/variables",
            "js/let",
            "js/const",
            "js/letVar",
            "js/ambito",
            "js/consoleLog",
            "js/hoisting",
            {
              type: "category",
              label: "Operadores",
              collapsed: true,
              items: [
                "js/operadores/operadores",
                "js/operadores/operadoresAritmeticos",
                "js/operadores/operadoresAsignacion",
                "js/operadores/operadoresComparacion",
                "js/operadores/operadoresConcatenacion",
                "js/operadores/operadoresLogicos",
                "js/operadores/precedenciaOperadores",
              ],
            },
            {
              type: "category",
              label: "Funciones",
              collapsed: true,
              items: [
                "js/funciones/funciones",
                "js/funciones/funcionesAnonimas",
                "js/funciones/funcionesAutoEjecutables",
                "js/funciones/funcionesPrimeraClase",
                "js/funciones/funcionesFlecha",
              ],
            },
            {
              type: "category",
              label: "Objetos_Literales",
              collapsed: true,
              items: [
                "js/objetos_literales/objetos_literales",
                "js/objetos_literales/this",
                "js/objetos_literales/todoSonObjetos",
              ],
            },
            {
              type: "category",
              label: "Strings",
              collapsed: true,
              items: [
                "js/strings/strings",
                "js/strings/metodosStrings",
                "js/strings/stringTemplates",
              ],
            },
            "js/numeros",
            {
              type: "category",
              label: "Arrays",
              collapsed: true,
              items: [
                "js/arrays/arrays",
                "js/arrays/interactuar",
                "js/arrays/metodosArrays",
              ],
            },
            "js/fechas",
            "js/math",
            "js/booleanos",
            "js/ifElse",
            "js/switch",
            {
              type: "category",
              label: "For",
              collapsed: true,
              items: ["js/for/for", "js/for/forIn", "js/for/forOf"],
            },
            "js/while",
            "js/breakContinue",
            "js/iterables",
            "js/sets",
            "js/typeof",
            "js/expresionesRegulares",
            "js/clases",
            {
              type: "category",
              label: "DOM",
              collapsed: true,
              items: [
                "js/dom/dom",
                "js/dom/introduccion",
                "js/dom/acceso",
                "js/dom/estructura",
                "js/dom/eventos",
                "js/dom/eventosUsuario",
                "js/dom/manipulacion",
                "js/dom/renderizacionReflujos",
              ],
            },
            "js/maps",
            "js/modulos",
            "js/depuracionCodigo",
            "js/asincronia",
            {
              type: "category",
              label: "Api Rest",
              collapsed: true,
              items: [
                "js/api/introduccion",
                "js/api/metodosHTTP",
                "js/api/endpoints",
                "js/api/headers",
                "js/api/codigosEstado",
                "js/api/asyncAwait",
                "js/api/autenticacionAutorizacion",
                "js/api/casosAvanzados",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "Programacion Orientada a Objetos",
          collapsed: true,
          items: [
            "poo/fundamentosPOO",
            "poo/objetos&prototipos",
            "poo/clases&metodos",
            "poo/herencia&polimorfismo",
            "poo/POOAplicada",
            "poo/buenasPracticas",
          ],
        },
        {
          type: "category",
          label: "Flexbox",
          collapsed: true,
          items: [
            "flex/introduccion",
            "flex/CSSvsFlexbox",
            "flex/ejesFlexbox",
            "flex/flexWrap",
            "flex/flexFlow",
            "flex/alignContent",
            "flex/order",
            "flex/flexGrow",
            "flex/flexShrink",
            "flex/flexBasis",
            "flex/alignSelf",
            {
              type: "category",
              label: "Actividades",
              collapsed: true,
              items: [
                "flex/actividades/actividadFlexWrap",
                "flex/actividades/actividadFlexFlow",
                "flex/actividades/actividadFlexGrow",
                "flex/actividades/actividadFlexShrink",
                "flex/actividades/proyectoNavbar",
                "flex/actividades/proyectoHero",
                "flex/actividades/proyectoGaleria",
                "flex/actividades/proyectoDemoInteractiva",
                "flex/actividades/proyectoFlexDemo",
              ],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Backend",
      collapsed: true,
      items: [
        "backend/introduction",
        {
          type: "category",
          label: "Bases de Datos Relacionales",
          collapsed: true,
          items: [
            "backend/databases/Modulo1_Que_es_una_base_de_datos_relacional",
            "backend/databases/Modulo2_Elementos_basicos_del_modelo_relacional",
            "backend/databases/Modulo3_Relaciones_y_cardinalidad",
            "backend/databases/Modulo4_Requisitos_de_informacion_y_diccionarios",
            "backend/databases/Modulo5_Modelado_conceptual_ER_UML",
            "backend/databases/Modulo6_Paso_a_modelo_logico_relacional",
            "backend/databases/Modulo7_Normalizacion",
            "backend/databases/Modulo8_Desnormalizacion_controlada",
            "backend/databases/Modulo9_Algebra_relacional_y_pensamiento_declarativo",
            "backend/databases/Modulo10_Joins_agrupaciones_y_filtros_avanzados",
            "backend/databases/Modulo11_Vistas_logicas_y_composicion_de_consulta",
            "backend/databases/Modulo12_Claves_e_integridad_referencial_avanzada",
            "backend/databases/Modulo13_Integridad_referencial_en_serio",
            "backend/databases/Modulo14_Validaciones_al_nivel_correcto_dominios_restricciones_y_reglas_de_negocio",
            "backend/databases/Modulo15_Tipos_de_dominios_practicos",
            "backend/databases/Modulo16_Tablas_puente_y_modelado_N-a-N",
            "backend/databases/Modulo17_Que_es_un_indice_y_como_usarlo",
            "backend/databases/Modulo18_Patrones_de_indexacion",
            "backend/databases/Modulo19_Planificacion_conceptual_de_consultas",
            "backend/databases/Modulo20_ACID_sin_humo",
            "backend/databases/Modulo21_Aislamiento_y_anomalias",
            "backend/databases/Modulo22_Modelo_de_privilegios_minimos",
            "backend/databases/Modulo23_Datos_sensibles_y_auditoria",
            "backend/databases/Modulo24_Consultas_parametrizadas_y_seguridad",
            "backend/databases/Modulo25_Capas_de_acceso_a_datos",
            "backend/databases/Modulo26_Control_de_cambios_del_esquema",
            "backend/databases/Modulo27_Pruebas_de_bases_de_datos",
            "backend/databases/Modulo28_Importacion_y_exportacion_fiable",
            "backend/databases/Modulo29_Vistas_materializadas_y_reportes",
            "backend/databases/Modulo30_Copias_de_seguridad_y_recuperacion",
            "backend/databases/Modulo31_Mantenimiento_de_indices_y_crecimiento",
            "backend/databases/Modulo32_Cambios_en_caliente",
            "backend/databases/Modulo33_Particionamiento_y_distribucion",
            "backend/databases/Modulo34_Replicacion_y_lectura_pesada",
            "backend/databases/Modulo35_Caches_y_colas",
            "backend/databases/Modulo36_Documentar_para_el_futuro",
          ],
        },
      ],
    },
  ],
};

export default sidebars;
